name: Coding Standards
on:
  pull_request:
    branches:
      - "main"
      - "*.x"
  push:
    branches:
      - "main"
      - "*.x"

jobs:
  coding-standards:
    name: Check Coding Standards
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_versions: ['7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{matrix.php_versions}}
          tools: cs2pr

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs -q --no-colors --report=checkstyle ./src | cs2pr
